spring.application.name=LoginAndSignup
#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql